# Generated by Django 4.2.13 on 2024-07-05 05:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_masterorigin_masterspecies_processing_roastlevel_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MasterSpecies',
            new_name='Origin',
        ),
        migrations.RenameModel(
            old_name='MasterOrigin',
            new_name='Species',
        ),
    ]
