# Generated by Django 4.2.13 on 2024-07-05 06:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_product_origin'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='processed',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='product.processing'),
        ),
        migrations.AddField(
            model_name='product',
            name='roast_level',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='product.roastlevel'),
        ),
        migrations.AddField(
            model_name='product',
            name='species',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='product.species'),
        ),
        migrations.AddField(
            model_name='product',
            name='tested',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='product.tested'),
        ),
    ]
